### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by cordoval** [cordoval/matthew-7-12#1]
Problem: Some countries have very strong limitations on the internet (Cuba mainly)

the idea of this project is to have a service that is configured to:
- email each commit as a patch to a configured email address for a given repository
- turn an email with patch attached into a PR with the correct sha1 base so that it can be rebased and merged
- produce on demand an email of multiple broken down zips attached of less than 2MB or such configurable limit  or passed limit and email them one by one to a given email address as a bootstrap repo process
- integrate Gush with this tool :+1:

**Comment by lukaszwit** [comment]
Sounds interesting. Are you sure that will actually help citizens of Cuba or similar?

**Comment by cordoval** [comment]
yes it will I am sure of that and I have beta testers

**Comment by cordoval** [comment]
laid out the architecture, kind of
