### ISSUE TITLE
logo call

### ISSUE THREAD

**Issue by cordoval** [cordoval/matthew-7-12#3]
@maxakawizard?

**Comment by MAXakaWIZARD** [comment]
What is this project about? Are there any ideas about logo?

**Comment by cordoval** [comment]
This project is a "Push/Pull Collaborative Git Over Mail" meaning it is an app that forwards to developers subscribed to a project the commits pushed to the repo as patches over email (pull) and also receives from contributing developers emails with patches attached to them turning them into PRs for the project they are contributing to. This is useful for slow or restricted connections.

The logo should be "a mount(ain) and a hand helping another hand"

**Comment by cordoval** [comment]
@MAXakaWIZARD thanks for taking action on this really! once again you are superb, in the middle of everything.

**Comment by MAXakaWIZARD** [comment]
@cordoval Ok, we'll try to find some spare time.

**Comment by cordoval** [comment]
thank you @MAXakaWIZARD looking forward to your great quality work!

**Comment by cordoval** [comment]
https://github.com/matthew-7-12 has already an account for the service connections, but probably needs an avatar as the logo as well

**Comment by cordoval** [comment]
how is it going @MAXakaWIZARD any questions or difficulties? let us know how we can help please

**Comment by MAXakaWIZARD** [comment]
@cordoval Sorry, didn't have time for that yet.

**Comment by MAXakaWIZARD** [comment]
PR #71
![matthew-logo-final](https://cloud.githubusercontent.com/assets/1138453/5146736/347e534e-71b8-11e4-9a3d-df0b5856777e.png)

**Comment by cordoval** [comment]
good catch @sstok

**Comment by sstok** [comment]
:) I was cleaning my notifications subscription list and saw this repository.
