### ISSUE TITLE
Pull is broken the Zipper dosen't work 

### ISSUE THREAD

**Issue by ysramirez** [cordoval/matthew-7-12#51]
1) Grace\UseCases\PullCodeTest::it_goes_through_the_whole_pull_flow with data set #0 (GET  

Array)
call_user_func_array() expects parameter 1 to be a valid callback, class 'Grace\Collabs\ZipperZippy' does not have a method 'pullCallback'
PHP Notice:  Array to string conversion in /home/aprendephp/mathew/matthew-7-12/deps/symfony/symfony/src/Symfony/Component/HttpFoundation/Request.php on line 492
PHP Stack trace:
PHP   1. {main}() /home/aprendephp/mathew/matthew-7-12/deps/phpunit/phpunit/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /home/aprendephp/mathew/matthew-7-12/deps/phpunit/phpunit/phpunit:55
PHP   3. PHPUnit_TextUI_Command->run() /home/aprendephp/mathew/matthew-7-12/deps/phpunit/phpunit/src/TextUI/Command.php:132
PHP   4. PHPUnit_TextUI_TestRunner->doRun() /home/aprendephp/mathew/matthew-7-12/deps/phpunit/phpunit/src/TextUI/Command.php:179
PHP   5. PHPUnit_TextUI_ResultPrinter->printResult() /home/aprendephp/mathew/matthew-7-12/deps/phpunit/phpunit/src/TextUI/TestRunner.php:432
PHP   6. PHPUnit_TextUI_ResultPrinter->printErrors() /home/aprendephp/mathew/matthew-7-12/deps/phpunit/phpunit/src/TextUI/ResultPrinter.php:169
PHP   7. PHPUnit_TextUI_ResultPrinter->printDefects() /home/aprendephp/mathew/matthew-7-12/deps/phpunit/phpunit/src/TextUI/ResultPrinter.php:314
PHP   8. PHPUnit_TextUI_ResultPrinter->printDefect() /home/aprendephp/mathew/matthew-7-12/deps/phpunit/phpunit/src/TextUI/ResultPrinter.php:243
PHP   9. PHPUnit_TextUI_ResultPrinter->printDefectHeader() /home/aprendephp/mathew/matthew-7-12/deps/phpunit/phpunit/src/TextUI/ResultPrinter.php:253
PHP  10. PHPUnit_Framework_TestCase->toString() /home/aprendephp/mathew/matthew-7-12/deps/phpunit/phpunit/src/TextUI/ResultPrinter.php:266
PHP  11. PHPUnit_Framework_TestCase->getDataSetAsString() /home/aprendephp/mathew/matthew-7-12/deps/phpunit/phpunit/src/Framework/TestCase.php:324
PHP  12. PHPUnit_Framework_TestCase->dataToString() /home/aprendephp/mathew/matthew-7-12/deps/phpunit/phpunit/src/Framework/TestCase.php:1751
PHP  13. Symfony\Component\HttpFoundation\Request->__toString() /home/aprendephp/mathew/matthew-7-12/deps/phpunit/phpunit/src/Framework/TestCase.php:1713

/home/aprendephp/mathew/matthew-7-12/src/Collabs/Collab.php:17
/home/aprendephp/mathew/matthew-7-12/src/UseCases/PullCodeTest.php:50

FAILURES!  
Tests: 1, Assertions: 0, Errors: 1.

**Comment by cordoval** [comment]
this problem has no description, besides it is obvious it is code that was just sketched. I was hoping you were able to understand the idea so that you can continue ironing it.
